# Generated by Django 6.1 on 2026-08-06 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('slug', models.SlugField(help_text="Used in the URL, e.g. 'basics'", max_length=70, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text="Used in the URL, e.g. 'reading-a-candlestick-chart'", max_length=220, unique=True)),
                ('excerpt', models.CharField(help_text='Short summary shown on the post card (1-2 sentences).', max_length=280)),
                ('body', models.TextField(help_text='Full post content. Plain text or basic HTML.')),
                ('is_published', models.BooleanField(default=True, help_text='Uncheck to hide this post from the site without deleting it.')),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.category')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
