# Generated by Django 6.1 on 2026-08-06 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text="Used in the URL, e.g. 'crypto-trading-fundamentals'", max_length=220, unique=True)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('description', models.TextField(help_text='Shown on the course card and detail page.')),
                ('lesson_count', models.PositiveIntegerField(default=0, help_text="Shown as '8 lessons'.")),
                ('hours', models.PositiveIntegerField(default=0, help_text="Shown as '4h total'.")),
                ('price', models.DecimalField(decimal_places=2, help_text='In Naira, e.g. 45000.00', max_digits=10)),
                ('selar_url', models.URLField(blank=True, help_text="Paste your Selar checkout link here. The 'Buy Course' button sends buyers here. Leave blank while you're still setting up the course on Selar -- the button will show as 'Coming soon'.")),
                ('is_published', models.BooleanField(default=True, help_text='Uncheck to hide this course without deleting it.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first. Use to control display order.')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.CharField(blank=True, max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
