# Generated by Django 6.1 on 2026-08-06 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="e.g. 'Bitcoin (BTC)' or 'USDT (TRC20)'", max_length=60)),
                ('address', models.CharField(max_length=200)),
                ('network_note', models.CharField(blank=True, help_text="Optional warning shown under the address, e.g. 'TRC20 network only -- other networks will lose funds.'", max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to stop showing this wallet without deleting it.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first.')),
            ],
            options={
                'ordering': ['order', 'label'],
            },
        ),
        migrations.RemoveField(
            model_name='course',
            name='selar_url',
        ),
        migrations.AddField(
            model_name='course',
            name='materials_url',
            field=models.URLField(blank=True, help_text="Link to the actual course materials (e.g. a private Google Drive folder or classroom link). Only shown to users you've granted access to below."),
        ),
        migrations.CreateModel(
            name='CourseAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, help_text="Optional, e.g. 'Paid 0.001 BTC, confirmed via email 3 Aug'", max_length=200)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Course access grants',
                'unique_together': {('user', 'course')},
            },
        ),
    ]
