# Generated by Django 6.1 on 2026-08-31 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_cryptowallet_remove_course_selar_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptowallet',
            name='qr_code',
            field=models.ImageField(blank=True, help_text='Upload the QR code image the client gave you for this wallet.', null=True, upload_to='wallet_qr/'),
        ),
    ]
