# Generated by Django 6.1 on 2026-09-29 23:31

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_cryptowallet_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='materials_url',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload the actual course video.', max_length=255, null=True, verbose_name='course video'),
        ),
    ]
